### ISSUE TITLE
why the dock is not autohide when i make full screen, this is extremely unconvinient 

### ISSUE THREAD

**Issue by ppvan** [manjaro-cutefish/download#10]

**Comment by yamunanga** [comment]
you can get full screen using 
alt+f3

**Comment by ppvan** [comment]
it 's work!
Thanks for the solution

**Comment by Yakumo-Yukari** [comment]
cutefish 0.3 The dock can already be auto-hidden

**Comment by hphilm** [comment]
The feature was added to 0.3. See also [upstream](https://github.com/cutefishos).
